wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    t:
      1:
      - 1
      4: 3.9.6
      5: 0.11.2
      8:
      - 5
amp:
  desc: null
  value: true
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 400
img_scale:
  desc: null
  value: 1.0
learning_rate:
  desc: null
  value: 0.0005
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
