wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1631281661
    t:
      1:
      - 1
      4: 3.8.10
      5: 0.12.1
      8:
      - 5
amp:
  desc: null
  value: true
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 200
img_scale:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 0.001
save_checkpoint:
  desc: null
  value: true
val_percent:
  desc: null
  value: 0.1
